compute_path_service: /ras_group8/global_planner
get_map_service: /ras_group8_map/map 
 

map_costs: 
  solid_obstacle: 100
  removable_obstacle: 50
  distance_obstacle: 50 
  free_cells: 1

obstacle_avoidance: 
  obstacle_boundary: 50
  obstacle_distance: 0.05


size_robot: 
  radius:  0.1
  
